export const SEED_DATA = []

export const SAMPLE_CONCERTS = [
  {
    id: 'demo-1',
    artist: 'Taylor Swift', date: '2023-07-04',
    venue: 'Johan Cruyff Arena', room: '', city: 'Amsterdam', country: 'Netherlands',
    type: 'concert', tour: 'The Eras Tour', support: ['Gracie Abrams'],
    friends: ['Sarah', 'Emma'], solo: false, rating: 5, ticketPrice: 149,
    merch: [{ item: 'Hoodie', price: '75' }, { item: 'T-shirt', price: '45' }],
    notes: 'Absolutely insane. 3 hours of perfection.',
    genre: 'Pop', subgenre: 'Indie pop', language: ['English'], venueSize: 'Stadium', seenAs: 'Headliner',
  },
  {
    id: 'demo-2',
    artist: 'Arctic Monkeys', date: '2023-06-12',
    venue: 'Ziggo Dome', room: '', city: 'Amsterdam', country: 'Netherlands',
    type: 'concert', tour: 'The Car Tour', support: ['Lana Del Rey'],
    friends: [], solo: true, rating: 4, ticketPrice: 75, merch: [], notes: '',
    genre: 'Rock', subgenre: 'Indie rock', language: ['English'], venueSize: 'Arena', seenAs: 'Headliner',
  },
  {
    id: 'demo-3',
    artist: 'NewJeans', date: '2024-01-27',
    venue: 'Ziggo Dome', room: '', city: 'Amsterdam', country: 'Netherlands',
    type: 'concert', tour: 'Bunnies Camp 2024', support: [],
    friends: ['Emma'], solo: false, rating: 5, ticketPrice: 99,
    merch: [{ item: 'Lightstick', price: '45' }], notes: '',
    genre: 'K-pop', subgenre: null, language: ['Korean', 'English'], venueSize: 'Arena', seenAs: 'Headliner',
  },
  {
    id: 'demo-4',
    artist: 'Bring Me The Horizon', date: '2022-11-08',
    venue: 'AFAS Live', room: '', city: 'Amsterdam', country: 'Netherlands',
    type: 'concert', tour: 'Post Human Tour', support: ['Spiritbox'],
    friends: ['Tom'], solo: false, rating: 4, ticketPrice: 45,
    merch: [{ item: 'T-shirt', price: '35' }], notes: '',
    genre: 'Metal', subgenre: null, language: ['English'], venueSize: 'Mid-venue', seenAs: 'Headliner',
  },
  {
    id: 'demo-5',
    artist: 'Tame Impala', date: '2021-09-15',
    venue: 'Paradiso', room: '', city: 'Amsterdam', country: 'Netherlands',
    type: 'concert', tour: '', support: [],
    friends: [], solo: true, rating: 5, ticketPrice: 35, merch: [],
    notes: 'Best show I have ever seen.',
    genre: 'Rock', subgenre: 'Alternative rock', language: ['English'], venueSize: 'Mid-venue', seenAs: 'Headliner',
  },
  {
    id: 'demo-6',
    artist: 'Coldplay', date: '2023-08-05',
    venue: 'Johan Cruyff Arena', room: '', city: 'Amsterdam', country: 'Netherlands',
    type: 'concert', tour: 'Music of the Spheres Tour', support: ['H.E.R.'],
    friends: ['Sarah', 'Emma', 'Tom'], solo: false, rating: 5, ticketPrice: 120,
    merch: [{ item: 'T-shirt', price: '45' }],
    notes: 'The wristbands and confetti made it magical.',
    genre: 'Pop', subgenre: 'Indie pop', language: ['English'], venueSize: 'Stadium', seenAs: 'Headliner',
  },
  {
    id: 'demo-7',
    artist: 'Lowlands 2022', date: '2022-08-19',
    venue: 'Walibi Holland', room: '', city: 'Biddinghuizen', country: 'Netherlands',
    type: 'festival', tour: '', support: [],
    friends: ['Sarah', 'Emma'], solo: false, rating: 4, ticketPrice: 235,
    merch: [{ item: 'Tote bag', price: '20' }],
    notes: '3 days of music. Incredible lineup.',
    genre: 'Pop', subgenre: null, language: ['English', 'Dutch'], venueSize: null, seenAs: 'Festival',
  },
  {
    id: 'demo-8',
    artist: 'Kendrick Lamar', date: '2023-05-02',
    venue: 'Ziggo Dome', room: '', city: 'Amsterdam', country: 'Netherlands',
    type: 'concert', tour: 'The Big Steppers Tour', support: ['Baby Keem'],
    friends: ['Tom'], solo: false, rating: 5, ticketPrice: 90, merch: [], notes: '',
    genre: 'Hip-Hop', subgenre: null, language: ['English'], venueSize: 'Arena', seenAs: 'Headliner',
  },
  {
    id: 'demo-9',
    artist: 'The 1975', date: '2024-02-28',
    venue: 'AFAS Live', room: '', city: 'Amsterdam', country: 'Netherlands',
    type: 'concert', tour: 'Still... At Their Very Best', support: [],
    friends: [], solo: true, rating: 4, ticketPrice: 55,
    merch: [{ item: 'Poster', price: '20' }], notes: '',
    genre: 'Rock', subgenre: 'Indie rock', language: ['English'], venueSize: 'Mid-venue', seenAs: 'Headliner',
  },
  {
    id: 'demo-10',
    artist: 'Billie Eilish', date: '2026-09-15',
    venue: 'Johan Cruyff Arena', room: '', city: 'Amsterdam', country: 'Netherlands',
    type: 'concert', tour: 'HIT ME HARD AND SOFT: THE TOUR', support: [],
    friends: ['Sarah'], solo: false, rating: null, ticketPrice: 95, merch: [], notes: '',
    genre: 'Pop', subgenre: null, language: ['English'], venueSize: 'Stadium', seenAs: 'Headliner',
  },
]

export const DEFAULT_SETTINGS = {
  topArtistsRows: 5,
  topFriendsRows: 8,
  topVenuesRows: 5,
  topExpensiveRows: 10,
  defaultTab: 'stats',
  defaultShowPast: 'closed',
  defaultStatsTab: 'summary',
  merchCategories: ['T-shirt','Hoodie','Crewneck','Tank top','Tote bag','Poster','Print','Hat / Cap','Beanie','Keychain','Pin / Badge','Wristband','Lightstick','Album','Vinyl','Other'],
  genres: ['Pop','K-pop','Rock','Electronic','Country','Hip-Hop','R&B','Metal','Folk','Jazz','Classical','Other'],
  subgenres: ['Indie pop','Dutch pop','Latin pop','Pop punk','Indie rock','Alternative rock','Folk rock','Drum & Bass','EDM','Dance','Singer-songwriter'],
  languages: ['English','Dutch','Spanish','French','German','Korean','Japanese','Portuguese','Other'],
  venueSizes: ['Club', 'Small hall', 'Mid-venue', 'Arena', 'Stadium'],
  colorTheme: 'purple',
  hiddenChartGroups: [],
  hiddenCharts: [],
  hiddenSummaryBlocks: [],
}

export const FRIENDS = []